server:
  port: 19094

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/order/**,/orders/**
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/product/**
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/auth/**
        discovery:
          locator:
            enabled: true   # Eureka ?? ?? ??? ??

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
    register-with-eureka: true
    fetch-registry: true

service:
  jwt:
    secret-key: "401b09eab3c013d4ca54922bb802bec8fd5318192b0a75f201d8b3727429080fb337591abd3e44453b954555b7a0812e1081c39b740293f765eae731f5a65ed1"
